### PR TITLE
feat(se-3116): add gpay to sprite

### PR DESCRIPTION
**Pull request by huilinn93**
we have a new payment method!

### CODE REVIEW

**Review by tlkiong — APPROVED** [review]
Google pay?

**Review by Andrew2ww — CHANGES_REQUESTED** [review]
GPay icon is too big, it wont be shown correct. Make it exactly 50x30 or put in 70x30 section

**Comment by amokashi-grepruby** [comment]
> Google pay?

@tlkiong Can you please take a look https://sephora-asia.atlassian.net/browse/SE-3116?focusedCommentId=244462 ?

**Comment by amokashi-grepruby** [comment]
> GPay icon is too big, it wont be shown correct. Make it exactly 50x30 or put in 70x30 section

I raised this size related issue and tagged UI-UX designer.
https://sephora-asia.atlassian.net/browse/SE-3116?focusedCommentId=244462

**Review by Andrew2ww — APPROVED** [review]

**Pull request merged**
