### PR TITLE
[KRO-93] Update icon sprite with FDK icons

### PR DESCRIPTION
**Pull request by abhinavmsra**

### CODE REVIEW

**Comment by tommi-lew** [comment]
Hey @abhinavmsra , I will try again. If you take a look at `app/assets/stylesheets/sephora_style_guide/variables/_icons.scss`, specifically from this line onwards..

` ------------------------------ Sprite icons congfig start ---------------------------`

It might give you some clue..

**Comment by abhinavmsra** [comment]
@tommi-lew I made the changes

**Comment by tommi-lew** [comment]
Can I ask for help to review these please? @zamakkat @ycewe @kieudongoctruc @ycewe

**Comment by tachyons** [comment]
line number 143 was a temporary workaround to get payments icons live before HK launch, we shouldn't be specifying classes from the app in the style guide. We need to follow the same pattern as before

**Comment by abhinavmsra** [comment]
@tachyons I was following this comment

> There should be a more suitable place, do take a look at #87

Can you share what is the pattern now?

**Comment by tachyons** [comment]
This https://github.com/sephora-sea/sephora-style-guide/blob/8f396a91cabbc0460744547113ecf6bd181ae9c0/app/assets/stylesheets/sephora_style_guide/variables/_icons.scss#L50 is the pattern to flow, I had to move wechat out of this because it wasn't placed in proper place in the sprite. Since all korean payments are placed in new line,you can follow the existing convention cc @zamakkat

**Comment by abhinavmsra** [comment]
@tachyons @tommi-lew I took some time today to understand how sprite classes are generated. It seems the script assumes the a row to be horizontally aligned & all icons in the row have same width.

Unfortunately thats not the case for Korea icons

I have following range of values

top: -301px, -302px, -304px
width: 25px, 31px, 35px;
height: 21px, 22px, 25px, 28px;

I will check with Caroline if this can be fixed

**Comment by donaldpiret** [comment]
@abhinavmsra which script are you referring to?

**Comment by abhinavmsra** [comment]
@donaldpiret this one

```
@mixin generate-sprite-icons($width: auto) {
  background-size: $width auto;

  @each $sprite-type, $sprite-details in $sephora-sprite {
    $height: map-get($sprite-details, 'height');
    $width: map-get($sprite-details, 'width');
    $col: map-get($sprite-details, 'col');
    $top: map-get($sprite-details, 'top');
    $classes: map-get($sprite-details, 'classes');
    $y_index: 0;

    &.#{$sprite-type} {
      height: #{$height};
      width: #{$width};
      $x_index: 0;

      @each $class in $classes {
        &.#{$class} {
          background-position: (-1 * $x_index * $width) ( (-1 * $y_index * $height) + $top);
        }

        $x_index: $x_index + 1;

        @if $x_index >= $col {
          $x_index: 0;
          $y_index: $y_index + 1;
        }
      }
    }
  }
}
```

**Comment by abhinavmsra** [comment]
The icons I have to use are not
1. Horizontally aligned
2. Do not start at 0px from the left
3. Are not of equal width & height

icons

**Comment by donaldpiret** [comment]
I wonder if this is the right time to start looking at a more robust method for generating sprites, eg. something like https://github.com/jakesgordon/sprite-factory (though that one seems like it's stopped getting maintained). @ycewe @kieudongoctruc any thoughts on this?

**Comment by abhinavmsra** [comment]
@tommi-lew @donaldpiret @tachyons I have updated this PR with new set of icons & recommended pattern to use sprites. Please review again

**Pull request merged**
